### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by Meisterschueler** [glidernet/python-ogn-client#44]
Happened 2017-12-13 between 15:12:12 and 15:34:53

Traceback (most recent call last):
  File "/Users/konstantin/Development/workspace/ogn-python/venv/bin/manage", line 11, in <module>
    sys.exit(main())
  File "/Users/konstantin/Development/workspace/ogn-python/venv/lib/python3.6/site-packages/manager/main.py", line 18, in main
    manager.main()
  File "/Users/konstantin/Development/workspace/ogn-python/venv/lib/python3.6/site-packages/manager/__init__.py", line 333, in main
    command.parse(args.all[1:])
  File "/Users/konstantin/Development/workspace/ogn-python/venv/lib/python3.6/site-packages/manager/__init__.py", line 130, in parse
    r = self(*args, **kwargs)
  File "/Users/konstantin/Development/workspace/ogn-python/venv/lib/python3.6/site-packages/manager/__init__.py", line 62, in __call__
    return self.run(*args, **kwargs)
  File "/Users/konstantin/Development/workspace/ogn-python/ogn/gateway/manage.py", line 37, in run
    client.run(callback=process_beacon, autoreconnect=True)
  File "/Users/konstantin/Development/workspace/ogn-python/venv/lib/python3.6/site-packages/ogn/client/client.py", line 66, in run
    packet_str = self.sock_file.readline().strip()
  File "/Users/konstantin/Development/workspace/ogn-python/venv/bin/../lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 688: invalid start byte

**Comment by Meisterschueler** [comment]
Solutions:
1. open the socket not as text but as binary
OR
2. add a catch clause and drop the message

**Comment by Meisterschueler** [comment]
Fixed with c2b82817c7439ae7b04009678ad05ce136709404
