### ISSUE TITLE
Library errors

### ISSUE THREAD

**Issue by smoothop3** [glidernet/python-ogn-client#55]
I get one or two of these errors per day at the moment:

Traceback (most recent call last):
  File "/flights/stations", line 303, in <module>
    client.run(callback=process_beacon, autoreconnect=True)
  File "/usr/local/lib/python3.6/dist-packages/ogn/client/client.py", line 74, in run
    callback(packet_str)
  File "/flights/stations", line 146, in process_beacon
    beacon = parse(raw_message)
  File "/usr/local/lib/python3.6/dist-packages/ogn/parser/parse.py", line 28, in parse
    aprs_type=message['aprs_type']))
  File "/usr/local/lib/python3.6/dist-packages/ogn/parser/parse.py", line 114, in parse_comment
    return parser.parse(aprs_comment, aprs_type)
  File "/usr/local/lib/python3.6/dist-packages/ogn/parser/aprs_comment/base.py", line 7, in parse
    data = self.parse_position(aprs_comment)
  File "/usr/local/lib/python3.6/dist-packages/ogn/parser/aprs_comment/spider_parser.py", line 15, in parse_position
    return {'address': ac_match.group('id'),
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by Meisterschueler** [comment]
Hello, thank you for the bug report. Is it possible to catch the Exception and print out the variable 'raw_message'?

**Comment by Meisterschueler** [comment]
Should be fixed with #60 . Otherwise @smoothop3 please reopen.
