### ISSUE TITLE
Tracker status without hardware version causes exception

### ISSUE THREAD

**Issue by matburnham** [glidernet/python-ogn-client#56]
After disabling some of the top-level exception handling to make it apparent, I get the following faitly quickly after starting ogn-python's gateway.

The error appears to be in parsing of the packet within python-ogn-client (or indeed a fault with the transmitter if these fields are mandatory, but the parser ought to handle permissively).

~~`OGN484D20>APRS,qAS,LHTAW01:/194518h4738.96N/01819.50E'188/007/A=000354 !W91! id07484D20 -058fpm +0.2rot 44.2dB 0e -0.1kHz gps3x4`~~
```
Traceback (most recent call last):
  File "./manage.py", line 13, in <module>
    manager.main()
  File "/home/mat/.virtualenvs/ogn-python/lib/python3.6/site-packages/manager/__init__.py", line 333, in main
    command.parse(args.all[1:])
  File "/home/mat/.virtualenvs/ogn-python/lib/python3.6/site-packages/manager/__init__.py", line 130, in parse
    r = self(*args, **kwargs)
  File "/home/mat/.virtualenvs/ogn-python/lib/python3.6/site-packages/manager/__init__.py", line 62, in __call__
    return self.run(*args, **kwargs)
  File "/home/mat/virtenvs/ogn-python/ogn/gateway/manage.py", line 52, in run
    client.run(callback=asdf, autoreconnect=True)
  File "/home/mat/.virtualenvs/ogn-python/lib/python3.6/site-packages/ogn/client/client.py", line 74, in run
    callback(packet_str)
  File "/home/mat/virtenvs/ogn-python/ogn/gateway/manage.py", line 22, in asdf
    message = string_to_message(raw_string, reference_date=datetime.utcnow())
  File "/home/mat/virtenvs/ogn-python/ogn/gateway/process.py", line 33, in string_to_message
    message = parse(raw_string, reference_date)
  File "/home/mat/.virtualenvs/ogn-python/lib/python3.6/site-packages/ogn/parser/parse.py", line 28, in parse
    aprs_type=message['aprs_type']))
  File "/home/mat/.virtualenvs/ogn-python/lib/python3.6/site-packages/ogn/parser/parse.py", line 114, in parse_comment
    return parser.parse(aprs_comment, aprs_type)
  File "/home/mat/.virtualenvs/ogn-python/lib/python3.6/site-packages/ogn/parser/aprs_comment/base.py", line 9, in parse
    data = self.parse_status(aprs_comment)
  File "/home/mat/.virtualenvs/ogn-python/lib/python3.6/site-packages/ogn/parser/aprs_comment/tracker_parser.py", line 33, in parse_status
    return {'hardware_version': int(match.group('hardware_version')) if match.group('hardware_version') else None,
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by Meisterschueler** [comment]
Hello @matburnham , thank you for the pull request. The problem is not in the "python-ogn-client" library. We have a old tracker message (you see the APRS as dstcall. The new tracker messages should have a OGNTRK as dstcall, but this is not the case here...
So the problem is in ogn-python.

**Comment by matburnham** [comment]
Ah I better go dig into it there as it'll now be a silent failure. Thanks.

**Comment by matburnham** [comment]
Hmmm. As an aside I've realised that the `OGN484D20>APRS,qAS,LHTAW01:/194518h4738.96N/01819.50E'188/007/A=000354 !W91! id07484D20 -058fpm +0.2rot 44.2dB 0e -0.1kHz gps3x4` message I quoted in my original issue comment doesn't seem to apply to the traceback. I must have done a bad copy/paste job when raising the issue. The test in the PR has a valid 'bad' message.

I started trying to write a test to apply to ogn-python to trace the problem, but following the code can't see how it could be caused in there:
1. ogn-python's `manage.py` sets up `python-ogn-client` with `client.run(callback=asdf, autoreconnect=True)`
2. The `asdf` callback calls `process.string_to_message`
3. The `process.string_to_message` function calls `ogn.parser.parse` (which is back in python-ogn-client land)
4. The exception is raised in `tracker_parser.py`.

Am I missing something?

This is an example OGNTRK message which also raises an exception:
```
OGN0332FC>OGNTRK,qAS,OxfBrtn2:>231801h Pilot=Pawel Base=Barton
Traceback (most recent call last):
  File "./manage.py", line 13, in <module>
    manager.main()
  File "/home/mat/.virtualenvs/ogn-python/lib/python3.6/site-packages/manager/__init__.py", line 333, in main
    command.parse(args.all[1:])
  File "/home/mat/.virtualenvs/ogn-python/lib/python3.6/site-packages/manager/__init__.py", line 130, in parse
    r = self(*args, **kwargs)
  File "/home/mat/.virtualenvs/ogn-python/lib/python3.6/site-packages/manager/__init__.py", line 62, in __call__
    return self.run(*args, **kwargs)
  File "/home/mat/virtenvs/ogn-python/ogn/gateway/manage.py", line 53, in run
    client.run(callback=asdf, autoreconnect=True)
  File "/home/mat/.virtualenvs/ogn-python/lib/python3.6/site-packages/ogn/client/client.py", line 74, in run
    callback(packet_str)
  File "/home/mat/virtenvs/ogn-python/ogn/gateway/manage.py", line 23, in asdf
    message = string_to_message(raw_string, reference_date=datetime.utcnow())
  File "/home/mat/virtenvs/ogn-python/ogn/gateway/process.py", line 33, in string_to_message
    message = parse(raw_string, reference_date)
  File "/home/mat/.virtualenvs/ogn-python/lib/python3.6/site-packages/ogn/parser/parse.py", line 28, in parse
    aprs_type=message['aprs_type']))
  File "/home/mat/.virtualenvs/ogn-python/lib/python3.6/site-packages/ogn/parser/parse.py", line 114, in parse_comment
    return parser.parse(aprs_comment, aprs_type)
  File "/home/mat/.virtualenvs/ogn-python/lib/python3.6/site-packages/ogn/parser/aprs_comment/base.py", line 9, in parse
    data = self.parse_status(aprs_comment)
  File "/home/mat/.virtualenvs/ogn-python/lib/python3.6/site-packages/ogn/parser/aprs_comment/tracker_parser.py", line 33, in parse_status
    return {'hardware_version': int(match.group('hardware_version')) if match.group('hardware_version') else None,
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by acasadoalonso** [comment]
Mat
You started to receive status messages versus position messages
Note the difference between :/ and :>
The parsing is different
In particular that APRS message is an OGN tracker status message with information about battery level, pilot name, etc 
The python-ogn-client needs to be updated for that
Cheers

Enviado desde mi iPhone.
AC/.

**Comment by Meisterschueler** [comment]
Okay, thank you, now I see the problem:
`OGN0332FC>OGNTRK,qAS,OxfBrtn2:>231801h Pilot=Pawel Base=Barton`

Someone again invented a new Tracker format. Without hardware and software (we could make them optional, as @matburnham already suggested), but what to do with the Part "Pilot=Pawel Base=Barton"? This seems to be a sort of comment. Until now comments are available at receiver beacon messages in the position message, but this is a status message... I am not so very happy with this non standard beacon and I would just kick it.

**Comment by acasadoalonso** [comment]
This message is only from OGN tracker (OGNTRK) devices
You can expect different types of status messages from some other devices in the future, all of them a free form.

Enviado desde mi iPhone.
AC/.
