### ISSUE TITLE
Cannot parse RND... message

### ISSUE THREAD

**Issue by Meisterschueler** [glidernet/python-ogn-client#58]
ERROR: test_50_live_messages (tests.client.test_AprsClient.AprsClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/glidernet/python-ogn-client/tests/client/test_AprsClient.py", line 145, in test_50_live_messages
    client.run(callback=process_message, autoreconnect=True)
  File "/home/travis/build/glidernet/python-ogn-client/ogn/client/client.py", line 74, in run
    callback(packet_str)
  File "/home/travis/build/glidernet/python-ogn-client/tests/client/test_AprsClient.py", line 132, in process_message
    message = parse(raw_message)
  File "/home/travis/build/glidernet/python-ogn-client/ogn/parser/parse.py", line 24, in parse
    message = parse_aprs(aprs_message, reference_timestamp)
  File "/home/travis/build/glidernet/python-ogn-client/ogn/parser/parse.py", line 80, in parse_aprs
    raise AprsParseError(message)
nose.proxy.AprsParseError: This is not a valid APRS packet: `RND620002>APRS,qAS,ZrhUzh:/122542h6505.31S/18136.75Wg224/106/A=160313 !W31! id18620002 -850fpm -7.6rot FL1611.23 6.5dB 4e -19.5kHz gps11x17`

**Comment by Meisterschueler** [comment]
Invalid APRS messages (>180°W) are not the problem of the parser
