### ISSUE TITLE
Catch socket crash

### ISSUE THREAD

**Issue by Meisterschueler** [glidernet/python-ogn-client#6]
2016-05-01 00:44:18,443 - WARN - ogn.client.client - Read returns zero length string. Failure.  Orderly closeout
Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    manager.main()
  File "/Users/konstantin/Development/workspace/ogn-python/venv/lib/python3.5/site-packages/manager/**init**.py", line 333, in main
    command.parse(args.all[1:])
  File "/Users/konstantin/Development/workspace/ogn-python/venv/lib/python3.5/site-packages/manager/**init**.py", line 130, in parse
    r = self(_args, *_kwargs)
  File "/Users/konstantin/Development/workspace/ogn-python/venv/lib/python3.5/site-packages/manager/**init**.py", line 62, in **call**
    return self.run(_args, *_kwargs)
  File "/Users/konstantin/Development/workspace/ogn-python/ogn/gateway/manage.py", line 37, in run
    client.run(callback=process_beacon, autoreconnect=True)
  File "/Users/konstantin/Development/workspace/ogn-python/venv/lib/python3.5/site-packages/ogn/client/client.py", line 74, in run
    self.connect()
  File "/Users/konstantin/Development/workspace/ogn-python/venv/lib/python3.5/site-packages/ogn/client/client.py", line 32, in connect
    self.sock.connect((settings.APRS_SERVER_HOST, port))
ConnectionRefusedError: [Errno 61] Connection refused

**Comment by Meisterschueler** [comment]
2016-05-04 20:57:53,115 - INFO - ogn.client.client - Connect to OGN as anon-dev with filter 'full-feed'
Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    manager.main()
  File "/Users/konstantin/Development/workspace/ogn-python/venv/lib/python3.5/site-packages/manager/__init__.py", line 333, in main
    command.parse(args.all[1:])
  File "/Users/konstantin/Development/workspace/ogn-python/venv/lib/python3.5/site-packages/manager/__init__.py", line 130, in parse
    r = self(*args, **kwargs)
  File "/Users/konstantin/Development/workspace/ogn-python/venv/lib/python3.5/site-packages/manager/__init__.py", line 62, in __call__
    return self.run(*args, **kwargs)
  File "/Users/konstantin/Development/workspace/ogn-python/ogn/gateway/manage.py", line 34, in run
    client.connect()
  File "/Users/konstantin/Development/workspace/ogn-python/venv/lib/python3.5/site-packages/ogn/client/client.py", line 32, in connect
    self.sock.connect((settings.APRS_SERVER_HOST, port))
ConnectionRefusedError: [Errno 61] Connection refused

**Comment by Meisterschueler** [comment]
2016-05-07 15:47:55,064 - WARN - ogn.client.client - Read returns zero length string. Failure.  Orderly closeout
Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    manager.main()
  File "/Users/konstantin/Development/workspace/ogn-python/venv/lib/python3.5/site-packages/manager/__init__.py", line 333, in main
    command.parse(args.all[1:])
  File "/Users/konstantin/Development/workspace/ogn-python/venv/lib/python3.5/site-packages/manager/__init__.py", line 130, in parse
    r = self(*args, **kwargs)
  File "/Users/konstantin/Development/workspace/ogn-python/venv/lib/python3.5/site-packages/manager/__init__.py", line 62, in __call__
    return self.run(*args, **kwargs)
  File "/Users/konstantin/Development/workspace/ogn-python/ogn/gateway/manage.py", line 37, in run
    client.run(callback=process_beacon, autoreconnect=True)
  File "/Users/konstantin/Development/workspace/ogn-python/venv/lib/python3.5/site-packages/ogn/client/client.py", line 74, in run
    self.connect()
  File "/Users/konstantin/Development/workspace/ogn-python/venv/lib/python3.5/site-packages/ogn/client/client.py", line 32, in connect
    self.sock.connect((settings.APRS_SERVER_HOST, port))
TimeoutError: [Errno 60] Operation timed out

**Comment by Meisterschueler** [comment]
Not reproduceable with version 0.8.0
